export type LanguageCode = "en" | "hi" | "bn" | "ta" | "te";

export interface LanguageData {
  name: string;
  nativeName: string;
  translations: Record<string, string>;
}

export const languages: Record<LanguageCode, LanguageData> = {
  en: {
    name: "English",
    nativeName: "EN",
    translations: {
      appName: "Smart Bharat",
      appTagline: "AI-Powered Civic Companion",
      navHome: "Home",
      navCompanion: "AI Companion",
      navSchemes: "Schemes",
      navReport: "Report Issue",
      navTrack: "Track Requests",
      navCommunity: "Community",
      welcomeBack: "Welcome back",
      heroPrompt: "What can I help you with today?",
      askAiButton: "Ask AI",
      homeChatCard: "Chat with AI Companion",
      homeChatDesc: "Get instant answers and guidance on public services",
      homeSchemesCard: "Find Government Schemes",
      homeSchemesDesc: "Check eligibility for 500+ welfare schemes",
      homeReportCard: "Report a Public Issue",
      homeReportDesc: "Potholes, water leaks, or streetlights",
      homeTrackCard: "Track My Requests",
      homeTrackDesc: "Real-time status of applications and complaints",
      homeCommunityCard: "Join Citizen Community",
      homeCommunityDesc: "Local discussions, guides, and mutual aid",
      checkEligibility: "Check Your Eligibility",
      stepOf: "Step {current} of {total}",
      ageLabel: "Age",
      incomeLabel: "Annual Income Range",
      stateLabel: "State of Residence",
      categoryLabel: "Category (Social Class)",
      employmentLabel: "Employment Status",
      genderLabel: "Gender",
      continueBtn: "Continue",
      backBtn: "Back",
      checkEligBtn: "Check Eligibility",
      documentVault: "AI Document Vault",
      vaultSubtitle: "Upload documents securely for auto-verification",
      dropFileText: "Drop file here or click to browse",
      fileRequirements: "Aadhaar, PAN, Income Cert (PDF, JPG)",
      newRequest: "New Request",
      trackSubtitle: "Monitor all your applications, grievances, and schemes in one place.",
      totalRequests: "TOTAL",
      pendingRequests: "PENDING",
      inProgressRequests: "IN PROGRESS",
      resolvedRequests: "RESOLVED",
      askStatusExplain: "Ask AI for Status Summary",
      markResolved: "Mark Resolved",
      issueReporterTitle: "Civic Issue Portal",
      issueReporterSubtitle: "Report local infrastructure problems directly to authorities.",
      detectLocation: "Detect My Location",
      uploadProof: "Upload Proof Photo",
      submitTicket: "Submit Ticket",
      communityTitle: "Civic Circles",
      communitySubtitle: "Share blueprints, find local solutions, and collaborate with citizens.",
      writeGuide: "Write a Guide",
      solutionBlueprints: "Solution Blueprints",
      activeCircles: "Active Circles",
      searchGuides: "Search guides by title, tag, or author...",
      members: "members",
      joinCircle: "Join Circle",
      upvoteBtn: "Upvote",
      loginTitle: "Welcome Back",
      loginSubtitle: "Sign in to access your civic dashboard.",
      loginWithGoogle: "Sign in with Google",
      or: "or",
      mobileLogin: "Mobile Login",
      phonePlaceholder: "Phone Number",
      sendOtp: "Send OTP",
      enterOtp: "Enter 6-digit OTP",
      verifyOtp: "Verify & Login"
    }
  },
  hi: {
    name: "Hindi",
    nativeName: "हिन्दी",
    translations: {
      appName: "स्मार्ट भारत",
      appTagline: "एआई-संचालित नागरिक साथी",
      navHome: "मुख्य पृष्ठ",
      navCompanion: "एआई साथी",
      navSchemes: "योजनाएं",
      navReport: "समस्या रिपोर्ट",
      navTrack: "आवेदन ट्रैक",
      navCommunity: "समुदाय",
      welcomeBack: "आपका स्वागत है",
      heroPrompt: "आज मैं आपकी क्या सहायता कर सकता हूँ?",
      askAiButton: "एआई से पूछें",
      homeChatCard: "एआई साथी के साथ चैट करें",
      homeChatDesc: "सार्वजनिक सेवाओं पर तुरंत उत्तर और मार्गदर्शन प्राप्त करें",
      homeSchemesCard: "सरकारी योजनाएं खोजें",
      homeSchemesDesc: "500+ कल्याणकारी योजनाओं के लिए पात्रता जांचें",
      homeReportCard: "सार्वजनिक समस्या दर्ज करें",
      homeReportDesc: "गड्ढे, पानी का रिसाव या खराब स्ट्रीटलाइट",
      homeTrackCard: "मेरे आवेदन ट्रैक करें",
      homeTrackDesc: "आवेदनों और शिकायतों की वास्तविक समय स्थिति",
      homeCommunityCard: "नागरिक समुदाय से जुड़ें",
      homeCommunityDesc: "स्थानीय चर्चाएं, मार्गदर्शिकाएं और आपसी सहायता",
      checkEligibility: "अपनी पात्रता जांचें",
      stepOf: "चरण {current} का {total}",
      ageLabel: "आयु",
      incomeLabel: "वार्षिक आय सीमा",
      stateLabel: "निवास का राज्य",
      categoryLabel: "वर्ग (सामाजिक श्रेणी)",
      employmentLabel: "रोजगार की स्थिति",
      genderLabel: "लिंग",
      continueBtn: "आगे बढ़ें",
      backBtn: "पीछे",
      checkEligBtn: "पात्रता जांचें",
      documentVault: "एआई दस्तावेज़ वॉल्ट",
      vaultSubtitle: "स्वचालित सत्यापन के लिए दस्तावेज़ सुरक्षित रूप से अपलोड करें",
      dropFileText: "फ़ाइल यहाँ छोड़ें या ब्राउज़ करने के लिए क्लिक करें",
      fileRequirements: "आधार, पैन, आय प्रमाण पत्र (PDF, JPG)",
      newRequest: "नया अनुरोध",
      trackSubtitle: "अपने सभी आवेदनों, शिकायतों और योजनाओं को एक ही स्थान पर ट्रैक करें।",
      totalRequests: "कुल",
      pendingRequests: "लंबित",
      inProgressRequests: "प्रगति पर",
      resolvedRequests: "हल किया गया",
      askStatusExplain: "स्थिति सारांश के लिए एआई से पूछें",
      markResolved: "सुलझा हुआ चिह्नित करें",
      issueReporterTitle: "नागरिक समस्या पोर्टल",
      issueReporterSubtitle: "स्थानीय बुनियादी ढांचे की समस्याओं की रिपोर्ट सीधे अधिकारियों को करें।",
      detectLocation: "मेरी स्थिति का पता लगाएं",
      uploadProof: "प्रमाण फोटो अपलोड करें",
      submitTicket: "टिकट जमा करें",
      communityTitle: "नागरिक मंडल (Civic Circles)",
      communitySubtitle: "समाधान साझा करें, स्थानीय रास्ते खोजें और नागरिकों के साथ सहयोग करें।",
      writeGuide: "मार्गदर्शिका लिखें",
      solutionBlueprints: "समाधान खाका",
      activeCircles: "सक्रिय मंडल",
      searchGuides: "शीर्षक, टैग या लेखक द्वारा खोजें...",
      members: "सदस्य",
      joinCircle: "मंडल में शामिल हों",
      upvoteBtn: "अपवोट",
      loginTitle: "स्वागत है",
      loginSubtitle: "अपने नागरिक डैशबोर्ड तक पहुँचने के लिए साइन इन करें।",
      loginWithGoogle: "गूगल के साथ साइन इन करें",
      or: "या",
      mobileLogin: "मोबाइल लॉगिन",
      phonePlaceholder: "फ़ोन नंबर",
      sendOtp: "ओटीपी भेजें",
      enterOtp: "6-अंकीय ओटीपी दर्ज करें",
      verifyOtp: "सत्यापित करें और लॉगिन करें"
    }
  },
  bn: {
    name: "Bengali",
    nativeName: "বাংলা",
    translations: {
      appName: "স্মার্ট ভারত",
      appTagline: "এআই-চালিত নাগরিক সঙ্গী",
      navHome: "মূল পাতা",
      navCompanion: "এআই সঙ্গী",
      navSchemes: "পরিকল্পনা",
      navReport: "অভিযোগ জানান",
      navTrack: "আবেদন ট্র্যাক",
      navCommunity: "সম্প্রদায়",
      welcomeBack: "স্বাগতম",
      heroPrompt: "আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?",
      askAiButton: "এআই-কে জিজ্ঞাসা করুন",
      homeChatCard: "এআই সঙ্গীর সাথে চ্যাট করুন",
      homeChatDesc: "জনসাধারণের পরিষেবাগুলিতে তাত্ক্ষণিক উত্তর এবং নির্দেশিকা পান",
      homeSchemesCard: "সরকারী প্রকল্প খুঁজুন",
      homeSchemesDesc: "৫০০+ কল্যাণমূলক প্রকল্পের জন্য যোগ্যতা পরীক্ষা করুন",
      homeReportCard: "জনসাধারণের সমস্যা রিপোর্ট করুন",
      homeReportDesc: "রাস্তার গর্ত, জল লিক বা ভাঙা স্ট্রিটলাইট",
      homeTrackCard: "আমার অনুরোধ ট্র্যাক করুন",
      homeTrackDesc: "আবেদন এবং অভিযোগের রিয়েল-টাইম স্ট্যাটাস",
      homeCommunityCard: "নাগরিক সম্প্রদায়ে যোগ দিন",
      homeCommunityDesc: "স্থানীয় আলোচনা, নির্দেশিকা এবং পারস্পরিক সহায়তা",
      checkEligibility: "আপনার যোগ্যতা পরীক্ষা করুন",
      stepOf: "ধাপ {current} / {total}",
      ageLabel: "বয়স",
      incomeLabel: "বার্ষিক আয় পরিসীমা",
      stateLabel: "বসবাসের রাজ্য",
      categoryLabel: "বিভাগ (সামাজিক শ্রেণী)",
      employmentLabel: "কর্মসংস্থানের অবস্থা",
      genderLabel: "লিঙ্গ",
      continueBtn: "এগিয়ে যান",
      backBtn: "পিছনে",
      checkEligBtn: "যোগ্যতা পরীক্ষা করুন",
      documentVault: "এআই ডকুমেন্ট ভল্ট",
      vaultSubtitle: "স্বয়ংক্রিয় যাচাইকরণের জন্য নথিগুলি নিরাপদে আপলোড করুন",
      dropFileText: "ফাইল এখানে ড্রপ করুন বা ব্রাউজ করতে ক্লিক করুন",
      fileRequirements: "আধার, প্যান, আয় সার্টিফিকেট (PDF, JPG)",
      newRequest: "নতুন অনুরোধ",
      trackSubtitle: "আপনার সমস্ত আবেদন, অভিযোগ এবং প্রকল্পগুলি এক জায়গায় পর্যবেক্ষণ করুন।",
      totalRequests: "মোট",
      pendingRequests: "তুলে ধরা",
      inProgressRequests: "চলতি কাজ",
      resolvedRequests: "সমাধান হয়েছে",
      askStatusExplain: "স্ট্যাটাস সারাংশের জন্য এআই-কে বলুন",
      markResolved: "সমাধান হয়েছে চিহ্নিত করুন",
      issueReporterTitle: "নাগরিক সমস্যা পোর্টাল",
      issueReporterSubtitle: "স্থানীয় পরিকাঠামোর সমস্যা সরাসরি কর্তৃপক্ষকে জানান।",
      detectLocation: "আমার অবস্থান সনাক্ত করুন",
      uploadProof: "প্রমাণ ফটো আপলোড করুন",
      submitTicket: "টিকিট জমা দিন",
      communityTitle: "নাগরিক সার্কেল",
      communitySubtitle: "সমাধানগুলি ভাগ করুন, স্থানীয় উপায় খুঁজুন এবং নাগরিকদের সাথে সহযোগিতা করুন।",
      writeGuide: "একটি নির্দেশিকা লিখুন",
      solutionBlueprints: "সমাধান ব্লুপ্রিন্ট",
      activeCircles: "সক্রিয় সার্কেল",
      searchGuides: "শিরোনাম, ট্যাগ বা লেখক দ্বারা অনুসন্ধান করুন...",
      members: "সদস্য",
      joinCircle: "সার্কেলে যোগ দিন",
      upvoteBtn: "আপভোট",
      loginTitle: "স্বাগতম",
      loginSubtitle: "আপনার নাগরিক ড্যাশবোর্ডে প্রবেশ করতে লগইন করুন।",
      loginWithGoogle: "গুগল দিয়ে সাইন ইন করুন",
      or: "অথবা",
      mobileLogin: "মোবাইল লগইন",
      phonePlaceholder: "ফোন নম্বর",
      sendOtp: "ওটিপি পাঠান",
      enterOtp: "৬ সংখ্যার ওটিপি লিখুন",
      verifyOtp: "যাচাই করুন এবং লগইন করুন"
    }
  },
  ta: {
    name: "Tamil",
    nativeName: "தமிழ்",
    translations: {
      appName: "ஸ்மார்ட் பாரத்",
      appTagline: "AI-இயங்கும் குடிமைத் துணை",
      navHome: "முகப்பு",
      navCompanion: "AI துணை",
      navSchemes: "திட்டங்கள்",
      navReport: "பிரச்சனை புகார்",
      navTrack: "விண்ணப்ப கண்காணிப்பு",
      navCommunity: "சமூகம்",
      welcomeBack: "நல்வரவு",
      heroPrompt: "இன்று நான் உங்களுக்கு எவ்வாறு உதவ முடியும்?",
      askAiButton: "AI-யிடம் கேள்",
      homeChatCard: "AI துணையுடன் அரட்டையடிக்கவும்",
      homeChatDesc: "பொது சேவைகள் குறித்த உடனடி பதில்களையும் வழிகாட்டுதலையும் பெறுங்கள்",
      homeSchemesCard: "அரசு திட்டங்களைக் கண்டறியவும்",
      homeSchemesDesc: "500+ நலத்திட்டங்களுக்கான தகுதியைச் சரிபார்க்கவும்",
      homeReportCard: "பொதுப் பிரச்சனையைப் புகாரளிக்கவும்",
      homeReportDesc: "சாலைப் பள்ளங்கள், குடிநீர் கசிவு அல்லது மின்விளக்கு பழுது",
      homeTrackCard: "என் விண்ணப்பங்களைக் கண்காணிக்கவும்",
      homeTrackDesc: "விண்ணப்பங்கள் மற்றும் புகார்களின் நிகழ்நேர நிலை",
      homeCommunityCard: "குடிமக்கள் சமூகத்தில் இணையுங்கள்",
      homeCommunityDesc: "உள்ளூர் விவாதங்கள், வழிகாட்டிகள் மற்றும் பரஸ்பர உதவி",
      checkEligibility: "உங்கள் தகுதியைச் சரிபார்க்கவும்",
      stepOf: "படி {current} / {total}",
      ageLabel: "வயது",
      incomeLabel: "ஆண்டு வருமான வரம்பு",
      stateLabel: "வசிக்கும் மாநிலம்",
      categoryLabel: "பிரிவு (சமூக வகுப்பு)",
      employmentLabel: "வேலைவாய்ப்பு நிலை",
      genderLabel: "பாலினம்",
      continueBtn: "தொடரவும்",
      backBtn: "பின்செல்",
      checkEligBtn: "தகுதியைச் சரிபார்",
      documentVault: "AI ஆவணக் காப்பகம்",
      vaultSubtitle: "தானியங்கி சரிபார்ப்புக்கு ஆவணங்களைப் பாதுகாப்பாகப் பதிவேற்றவும்",
      dropFileText: "கோப்பை இங்கே இழுத்து விடவும் அல்லது தேட கிளிக் செய்யவும்",
      fileRequirements: "ஆதார், பான், வருமானச் சான்றிதழ் (PDF, JPG)",
      newRequest: "புதிய கோரிக்கை",
      trackSubtitle: "உங்கள் விண்ணப்பங்கள், புகார்கள் மற்றும் திட்டங்களை ஒரே இடத்தில் கண்காணிக்கவும்.",
      totalRequests: "மொத்தம்",
      pendingRequests: "நிலுவையில்",
      inProgressRequests: "செயல்பாட்டில்",
      resolvedRequests: "தீர்வு காணப்பட்டது",
      askStatusExplain: "நிலை சுருக்கத்திற்கு AI-யிடம் கேளுங்கள்",
      markResolved: "தீர்க்கப்பட்டதாகக் குறிக்கவும்",
      issueReporterTitle: "குடிமக்கள் குறை தீர்க்கும் மையம்",
      issueReporterSubtitle: "உள்ளூர் உள்கட்டமைப்பு பிரச்சினைகளை நேரடியாக அதிகாரிகளிடம் புகாரளிக்கவும்.",
      detectLocation: "இருப்பிடத்தைக் கண்டறி",
      uploadProof: "புகைப்பட ஆதாரத்தைப் பதிவேற்று",
      submitTicket: "புகாரைச் சமர்ப்பி",
      communityTitle: "குடிமக்கள் வட்டங்கள்",
      communitySubtitle: "வழிகாட்டிகளைப் பகிரவும், உள்ளூர் தீர்வுகளைக் கண்டறியவும், குடிமக்களுடன் ஒத்துழைக்கவும்.",
      writeGuide: "வழிகாட்டி எழுது",
      solutionBlueprints: "தீர்வு திட்டங்கள்",
      activeCircles: "செயலில் உள்ள வட்டங்கள்",
      searchGuides: "தலைப்பு, குறிச்சொல் அல்லது ஆசிரியர் மூலம் தேடுங்கள்...",
      members: "உறுப்பினர்கள்",
      joinCircle: "வட்டத்தில் இணை",
      upvoteBtn: "வாக்களி",
      loginTitle: "வரவேற்கிறோம்",
      loginSubtitle: "உங்கள் டாஷ்போர்டை அணுக உள்நுழையவும்.",
      loginWithGoogle: "Google மூலம் உள்நுழைக",
      or: "அல்லது",
      mobileLogin: "கைபேசி உள்நுழைவு",
      phonePlaceholder: "தொலைபேசி எண்",
      sendOtp: "OTP அனுப்பு",
      enterOtp: "6-இலக்க OTP-ஐ உள்ளிடவும்",
      verifyOtp: "சரிபார்த்து உள்நுழை"
    }
  },
  te: {
    name: "Telugu",
    nativeName: "తెలుగు",
    translations: {
      appName: "స్మార్ట్ భారత్",
      appTagline: "AI-ఆధారిత పౌర సహాయకుడు",
      navHome: "హోమ్",
      navCompanion: "AI సహాయకుడు",
      navSchemes: "పథకాలు",
      navReport: "సమస్య నివేదిక",
      navTrack: "దరఖాస్తు ట్రాకింగ్",
      navCommunity: "కమ్యూనిటీ",
      welcomeBack: "స్వాగతం",
      heroPrompt: "ఈ రోజు నేను మీకు ఏ విధంగా సహాయం చేయగలను?",
      askAiButton: "AIని అడగండి",
      homeChatCard: "AI సహాయకుడితో చాట్ చేయండి",
      homeChatDesc: "ప్రభుత్వ సేవలపై తక్షణ సమాధానాలు మరియు మార్గదర్శకత్వం పొందండి",
      homeSchemesCard: "ప్రభుత్వ పథకాలను కనుగొనండి",
      homeSchemesDesc: "500+ సంక్షేమ పథకాలకు అర్హతను తనిఖీ చేయండి",
      homeReportCard: "పౌర సమస్యను నివేదించండి",
      homeReportDesc: "రోడ్డు గుంతలు, నీటి లీకేజీలు లేదా వీధి దీపాల సమస్యలు",
      homeTrackCard: "నా దరఖాస్తులను ట్రాక్ చేయండి",
      homeTrackDesc: "దరఖాస్తులు మరియు ఫిర్యాదుల నిజ-సమయ స్థితి",
      homeCommunityCard: "పౌర సమూహంలో చేరండి",
      homeCommunityDesc: "స్థానిక చర్చలు, గైడ్‌లు మరియు పరస్పర సహాయం",
      checkEligibility: "మీ అర్హతను తనిఖీ చేయండి",
      stepOf: "దశ {current} / {total}",
      ageLabel: "వయస్సు",
      incomeLabel: "వార్షిక ఆదాయ పరిమితి",
      stateLabel: "నివాస రాష్ట్రం",
      categoryLabel: "వర్గం (సామాజిక వర్గం)",
      employmentLabel: "ఉద్యోగ స్థితి",
      genderLabel: "లింగం",
      continueBtn: "కొనసాగించు",
      backBtn: "వెనుకకు",
      checkEligBtn: "అర్హత తనిఖీ",
      documentVault: "AI డాక్యుమెంట్ వాల్ట్",
      vaultSubtitle: "ఆటో-వెరిఫికేషన్ కోసం పత్రాలను సురక్షితంగా అప్‌లోడ్ చేయండి",
      dropFileText: "ఫైల్‌ను ఇక్కడ వదలండి లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి",
      fileRequirements: "ఆధార్, పాన్, ఆదాయ ధృవీకరణ పత్రం (PDF, JPG)",
      newRequest: "కొత్త అభ్యర్థన",
      trackSubtitle: "మీ దరఖాస్తులు, ఫిర్యాదులు మరియు పథకాలను ఒకే చోట పర్యవేక్షించండి.",
      totalRequests: "మొత్తం",
      pendingRequests: "పెండింగ్",
      inProgressRequests: "పురోగతిలో ఉంది",
      resolvedRequests: "పరిష్కరించబడింది",
      askStatusExplain: "స్థితి సారాంశం కోసం AIని అడగండి",
      markResolved: "పరిష్కరించబడినట్లు గుర్తించు",
      issueReporterTitle: "పౌర సమస్యల పోర్టల్",
      issueReporterSubtitle: "స్థానిక సమస్యలను నేరుగా అధికారులకు నివేదించండి.",
      detectLocation: "నా స్థానాన్ని గుర్తించు",
      uploadProof: "ఫోటో ఆధారాన్ని అప్‌లోడ్ చేయి",
      submitTicket: "సమర్పించు",
      communityTitle: "పౌర సర్కిల్‌లు",
      communitySubtitle: "పరిష్కారాలను పంచుకోండి, స్థానిక మార్గాలను కనుగొనండి మరియు పౌరులతో కలిసి పనిచేయండి.",
      writeGuide: "గైడ్ రాయండి",
      solutionBlueprints: "పరిష్కార బ్లూప్రింట్లు",
      activeCircles: "యాక్టివ్ సర్కిల్స్",
      searchGuides: "శీర్షిక, ట్యాగ్ లేదా రచయిత ద్వారా శోధించండి...",
      members: "సభ్యులు",
      joinCircle: "సర్కిల్‌లో చేరండి",
      upvoteBtn: "అప్‌వోట్",
      loginTitle: "స్వాగతం",
      loginSubtitle: "మీ పౌర డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి లాగిన్ చేయండి.",
      loginWithGoogle: "Googleతో లాగిన్ అవ్వండి",
      or: "లేదా",
      mobileLogin: "మొబైల్ లాగిన్",
      phonePlaceholder: "ఫోన్ నంబర్",
      sendOtp: "OTP పంపు",
      enterOtp: "6-అంకెల OTPని నమోదు చేయండి",
      verifyOtp: "ధృవీకరించి లాగిన్ అవ్వండి"
    }
  }
};

export function getTranslation(lang: LanguageCode, key: string, params?: Record<string, string>): string {
  const langData = languages[lang] || languages.en;
  let text = langData.translations[key] || languages.en.translations[key] || key;
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });
  }
  return text;
}
